---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-metrics
  namespace: arc-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-metrics-reader
  namespace: arc-runners
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-metrics-binding
  namespace: arc-runners
subjects:
  - kind: ServiceAccount
    name: runner-metrics
    namespace: arc-runners
roleRef:
  kind: Role
  name: pod-metrics-reader
  apiGroup: rbac.authorization.k8s.io
